### ISSUE TITLE
Device 'Shots=0' argument breaks down for the SF plugin

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane-sf#23]
The SF plugin has not been updated with PL Device reconfiguration where the user is not explicitly required to give 'shots=0' argument anymore. This produces the following bug when running files that use SF plugin:

```pennylane._device.DeviceError: The specified number of shots needs to be at least 1. Got 0.```

*See https://github.com/XanaduAI/pennylane/issues/334*

**Comment by AroosaIjaz** [comment]
@josh146, even after reinstalling the plugin, if I run `make docs` on the master PL branch, I still see the same error:

```
Unexpected failing examples:
/home/aroosa/pennylane/examples/pennylane_run_plugins_hybrid.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/aroosa/conda3/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 480, in _memory_usage
    out = func()
  File "/home/aroosa/conda3/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/home/aroosa/pennylane/examples/pennylane_run_plugins_hybrid.py", line 131, in <module>
    dev_fock = qml.device("strawberryfields.fock", wires=2, cutoff_dim=2)
  File "/home/aroosa/pennylane/pennylane/__init__.py", line 204, in device
    return plugin_device_class(*args, **options)
  File "/home/aroosa/conda3/lib/python3.7/site-packages/pennylane_sf/fock.py", line 100, in __init__
    super().__init__(wires, shots=shots, hbar=hbar)
  File "/home/aroosa/conda3/lib/python3.7/site-packages/pennylane_sf/simulator.py", line 68, in __init__
    super().__init__(wires, shots)
  File "/home/aroosa/pennylane/pennylane/_device.py", line 121, in __init__
    self.shots = shots
  File "/home/aroosa/pennylane/pennylane/_device.py", line 194, in shots
    raise DeviceError("The specified number of shots needs to be at least 1. Got {}.".format(shots))
pennylane._device.DeviceError: The specified number of shots needs to be at least 1. Got 0.
```
It might be a plugin update issue. Should I update from the github repo of the plugin? I just redid the `pip install ` command.

**Comment by co9olguy** [comment]
Yes, the update has not propagated into a release of pennylane-sf

**Comment by co9olguy** [comment]
but I think it's relatively safe for us to make a bugfix release, @josh146 ?

**Comment by co9olguy** [comment]
@AroosaIjaz you will need to install from master of `pennylane-sf`

**Comment by josh146** [comment]
We shouldn't make a bugfix release until PL core has a bugfix release.

Currently,
* PL master and PL-SF master are compatible
* PL pip and PL-SF pip are compatible.
